@ContosoPizza_HostAddress = http://localhost:5127

GET {{ContosoPizza_HostAddress}}/ContosoPizza/1
Accept: applicationo/json

###

GET {{ContosoPizza_HostAddress}}/ContosoPizza/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/WeatherForecast/
Accept: application/json

###

Post {{ContosoPizza_HostAddress}}/ContosoPizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isBlutenFree": false,
    "price": 6.5
}

###

PUT {{ContosoPizza_HostAddress}}/ContosoPizza/1
Content-Type: application/json

{
    "id": 1,
    "name": "Margarita Updated",
    "isBlutenFree": true,
    "price": 10.0
}

###

DELETE {{ContosoPizza_HostAddress}}/ContosoPizza/1
Accept: application/json

###